name: Test

permissions: write-all

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      if: github.event_name == 'pull_request'
      run: go test -v ./...

    - name: Generate coverage report
      if: github.event_name == 'push'
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: Check test coverage
      if: github.event_name == 'push'
      uses: vladopajic/go-test-coverage@v2
      with:
        profile: cover.out
        local-prefix: github.com/iskandervdh/vorn
        threshold-total: 90

        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        git-branch: badges
